### ISSUE TITLE
Links do rodapé precisam ser visíveis

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/cc-chooser#1]
Podemos colocar um underline bem leve nos dois links do rodapé?

![screen shot 2017-05-16 at 09 37 44](https://cloud.githubusercontent.com/assets/3904166/26106134/548a1640-3a1b-11e7-8a62-9af3c8869fff.png)

**Comment by greevin** [comment]
Na verdade, são 3 links que existem no footer e adicionei o text-decoration: underline em cada um deles.

![captura](https://cloud.githubusercontent.com/assets/7833013/26106845/aa9ce434-3a1d-11e7-8a8b-bd015ff96bc5.png)
