### ISSUE TITLE
Underline no link das principais e mudança na tela

### ISSUE THREAD

**Issue by tamielbr** [tamielbr/cc-chooser#3]
Dois em um:

- Temos uns links aqui que precisam ter underline leve também.

- Podemos usar uma separação em duas coisas: Uma para o texto de  **ASSISTENTES** e outro para  **NOTAS** (ou seja, duas caixas) podemos usar uma cor diferente para cada. Com essa mudança, podemos eliminar o cabeçalho **Notas**.

![screen shot 2017-05-16 at 11 34 32](https://cloud.githubusercontent.com/assets/3904166/26111606/efec492c-3a2b-11e7-8da1-345b3ca12f99.png)

**Comment by greevin** [comment]
Alterado a página inicial para que os textos aparecessem em dois panels chamados 'Assistentes' e 'Notas'. Além de acrescentar text-decoration: underline para todos os links.

![teste](https://cloud.githubusercontent.com/assets/7833013/26128158/d243b56e-3a61-11e7-9256-aa1323f5ff58.png)
